DROP DATABASE PI_3S;
CREATE DATABASE PI_3S;

USE PI_3S;

CREATE TABLE User 
(
	ID_User INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(200) NOT NULL DEFAULT '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
    Data_Criacao DATETIME NOT NULL DEFAULT NOW(),
    Ultimo_Acesso DATETIME NULL,
    Senha_Redefinida BOOLEAN DEFAULT TRUE
);

CREATE TABLE Role
(
	Role_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Role VARCHAR(25)
);

CREATE TABLE User_Role
(
	Id_User_Role INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_user INT NOT NULL,
    Role_ID INT NOT NULL,
    
    CONSTRAINT FK_ID_User FOREIGN KEY(ID_User)
		REFERENCES user(ID_User),
    CONSTRAINT FK_Role_ID FOREIGN KEY(Role_ID)
		REFERENCES role(Role_ID)        
);